### ISSUE TITLE
mein Vorschlag ;-)

### ISSUE THREAD

**Issue by Wegelagerin** [Hyperthrust/central-source#1]
central-source

Hyperthrust the Free Software Project

Why we named it Hyperthrust?

Because one of our Core Developers is a fan of "Streethawk" a vintage 80's TV Show ;-)

Why not OpenSource?

We love OpenSource but we considered that the GNU Freesoftware philosophy fits better to our Project.

Project Objectives

Provide a free "Group software" (ich weiß nicht ob das so geht oder etwas anderes aussagt!) and Communicationserver Network? for Posix and Non-Posix Operatingsystems
Maximum security and codequality combined with our best abilities plus constant learning and improvement.
Democratic community process (final decisions are made by the community elected Core Development Team) _>demokratisch sagt das ja schon aus würde ich also weg lassen
Feel  free to use and modify our work as you want (within the rules the GNU GPL license defines)
We follow a TDD and Regressiontesting approach to verify the code and scaleability.
Embedded LUA-Scripting within the Core-Serversystem to allow custom user Scripts.
Providing easy to use API' and proper SDK's for C/C++. C#, Delphi/Lazarus, VB-Script and LUA

How to contribute? oder If you want to contribute!

Test the stability of the Software, hunt and track down bugs
Report any Issue (please file an issue if you find a bug, a usability problem or anything else)
Feel wlcome to help and solve Problems in a friendly and cooperative manner.
Recommend our Project if you like it ;-)
Non-Depedency policy

The first approach to implement a feature is allways to implement it ourselfs, without the need of thirdparty libs and code.
We support Open Standards as SMTP, IMAP, OPUS, TLS, AES and Diffie-Hellman

**Comment by Dravion** [comment]
Thx, i will take a look on it, please be patient ;-)

**Comment by promi** [comment]
Thanks for the feedback, I just improved the README file.
